version: "3"
services:

  postgres12:
    image: postgres:12
    container_name: easyrates-postgres12
    environment:
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 5433:5432  
    networks:
      - easyrates

networks:
  easyrates:
    driver: bridge